name: Prettier Format

on: push

jobs:
  code_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Prettier Format
        run: npm run format
      - name: Config git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Commit and push
        run: |
          if [[ -n $(git status --porcelain) ]]
          then
            git add .
            git commit -m 'chore: format code'
            git push
          else
            echo "Nothing to commit."
          fi
