name: Format and Lint Code

on: push

jobs:
  code_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Prettier Format
        run: npm run format
      - name: Config git
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
      - name: Commit and push
        run: |
          if [[ -n $(git status --porcelain) ]]
          then
            git add .
            git commit -m 'chore: format code'
            git push
          else
            echo "Nothing to commit."
          fi
  code_check:
    runs-on: ubuntu-latest
    needs: code_format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: ESLint Check
        id: check-code
        run: |
          check_output=$(npm run --silent check || :)
          check_failed=$([[ -z "$check_output" ]] && echo 'false' || echo 'true')
          check_output=$(echo -e "\`\`\`${check_output}\n\`\`\`")
          check_output="${check_output//'%'/'%25'}"
          check_output="${check_output//$'\n'/'%0A'}"
          check_output="${check_output//$'\r'/'%0D'}"
          echo ::set-output name=check_output::"$check_output"
          echo ::set-output name=check_failed::"$check_failed"
      - name: Comment if check failed
        uses: peter-evans/commit-comment@v1
        if: ${{ 'true' == steps.check-code.outputs.check_failed }}
        with:
          body: ${{ steps.check-code.outputs.check_output }}
      - name: Error if check failed
        if: ${{ 'true' == steps.check-code.outputs.check_failed }}
        run: exit -1
